Add BotRemoteAngles and BotAngles
iw4x/iw4x-client pull request #113
Opened 2024-05-02 17:28 UTC by ineedbots

**What does this PR do?**

Add `BotRemoteAngles` and `BotAngles` builtin methods for bots

Fixes `ads` `BotAction` not throwing (allows bots to shoot akimbo weapons)

Adds `remote` `BotAction`

`BotStop` assigns current weapon

Thanks for the contribution! Please provide a concise description of the problem this request solves.

**How does this PR change IW4x's behaviour?**

Are there any breaking changes? Will any existing behaviour change?
Specify the new expected behaviour if this PR adds a new gameplay feature or alters an existing game mechanic. You may provide an image or video showing the changes.

**Anything else we should know?**

Add any other context about your changes here.

**Did you check all the boxes?**

- [ ] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] Mention any [related issues](https://github.com/XLabsProject/iw4x-client/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [ ] Follow our [coding conventions](https://github.com/XLabsProject/iw4x-client/blob/master/CODESTYLE.md)
- [ ] Minimize the number of commits

2024-05-03 08:55 UTC, Rackover requested changes
Some unsafe access of ptr needs to be fixed, otherwise looks okay 👍

2024-05-03 08:55 UTC, Rackover commented on src/Components/Modules/Bots.cpp
> +		GSC::Script::AddMethod("BotRemoteAngles", [](const Game::scr_entref_t entref) // Usage: <bot> BotRemoteAngles(<int>, <int>);
It is not immediatly obvious to me what a function called "BotRemoteAngles" does nor what its parameters are, without reading the implementation. It would be nice to document them (the function "sets" the yaw and pitch, even though none of these three word appear in the function name!)

Is there a reason why the "remote angles" is not set at the same time as the "angles" in the other function?
The code does not inform me on why they need to be done separately and the name in the engine ("remote angle") i'm not sure what it means in this context.

2024-05-03 08:55 UTC, Rackover commented on src/Components/Modules/Bots.cpp
> +			const auto* ent = GSC::Script::Scr_GetPlayerEntity(entref);
This function can return nullptr !
Please always check for nullptr before accessing the ent's members, lest a bad GSC script could instantly crash the game.

2024-05-03 08:55 UTC, Rackover commented on src/Components/Modules/Bots.cpp
> +			if (!Game::SV_IsTestClient(ent->s.number))
ditto!

2024-05-03 08:55 UTC, Rackover commented on src/Components/Modules/Bots.cpp
> +		{ "ads", Game::CMD_BUTTON_ADS | Game::CMD_BUTTON_THROW },
Would it be okay to map CMD_BUTTON_THROW to a new action named "throw" and then simply set both actions in GSC, therefore managing akimbo in GSC, rather than merging the commands in the client?

2024-05-03 15:42 UTC, Rackover commented on src/Components/Modules/Bots.cpp
> +			const auto* ent = GSC::Script::Scr_GetPlayerEntity(entref);
It also returns nullptr if it's not a player!

2024-05-03 16:13 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
> +			const auto* ent = GSC::Script::Scr_GetPlayerEntity(entref);
It's true, it can never be a null pointer because of the long jumps.
Because it was never marked as no return in the definitions at functions.hpp the compiler will complain so those return nullptrs are just there for that reason.
A refactor initiative would be to use c++ exceptions like here  https://git.alterware.dev/alterware/iw6-mod/src/branch/master/src/client/component/gsc/script_extension.cpp#L300

powered by this hook which uses try/catch https://git.alterware.dev/alterware/iw6-mod/src/branch/master/src/client/component/gsc/script_extension.cpp#L56

By using c++ exceptions to handle this in code it would no longer require to leave those nullptrs as the throw statement is already a no return
alternatively leave stuff as it is without any c++ stuff and either comment the behaviour of the function or mark objecterror and all other similar functions as no return

2024-05-03 19:57 UTC, Rackover commented on src/Components/Modules/Bots.cpp
> +			const auto* ent = GSC::Script::Scr_GetPlayerEntity(entref);
I see! :)
Indeed if the function is to never return it should be marked as noreturn and therefore those `return nullptr`  should not be there. Additional short comments (just saying "this long jumps out, no return needed" or something like that) would be much appreciated
The GSC VM is a part of the engine I almost never worked with so I'm just doing due dilligence of checking your implem, sorry if my remarks are a bit naive.
I looked a bit in the engine and the Scr_Error does call Sys_Error which is a noreturn, however there are several conditions to calling Sys_Error (0x2040D06  OR  !0x201A40F)  and they're not documented on my end, I'm not sure what they are.
Do you confirm that Scr_Error will always call Sys_Error and therefore never return?
If so I will trust your word and go through with your change, no problem, but if you're not sure please double check 🙇‍♀️

2024-05-09 21:54 UTC, Rackover approved these changes
I'm gonna check up every PR this saturday and draft a new release 💆‍♀️

2024-05-14 20:16 UTC, merged