update .github
iw4x/iw4x-client pull request #152
Opened 2024-10-10 11:34 UTC by mxve

- Resolves #115 
- Removed CODEOWNERS
  - From what I understand this is used to automatically assign reviewers. Using @iw4x/Developers does not work as its not public.
- Formatting fix on build.yml
- Fixed typo in README that was driving me insane

2024-10-10 15:49 UTC, diamante0018 requested changes

2024-10-10 15:49 UTC, diamante0018 commented on .github/workflows/build.yml
Please update everything here to use `@ v4` of github actions. using nodejs16 will throw warnings and is deprecated

2024-10-10 16:58 UTC, SnowyWhite commented
The [SECURITY.md](https://github.com/iw4x/iw4x-client/blob/develop/SECURITY.md) file has the mail address of momo, I think this PR would be a great opportunity to fix this too!

2024-10-12 15:41 UTC, diamante0018 commented
> The [SECURITY.md](https://github.com/iw4x/iw4x-client/blob/develop/SECURITY.md) file has the mail address of momo, I think this PR would be a great opportunity to fix this too!

Should be updated by a maintainer/project owner and not via a PR although I wouldn't know.. Perhaps open an issue about this for Louvenarde to see

2024-10-13 13:28 UTC, diamante0018 reviewed
updated build file looks good to me. this should get rid of the warnings from the actions tab

2024-10-13 14:11 UTC, Rackover approved these changes

2024-10-13 14:11 UTC, merged