Fix of fps drop when using a high polling rate mouse
iw4x/iw4x-client pull request #166
Opened 2024-11-09 21:21 UTC by L3D451R7

This pull request fixes an fps drop caused by bottleneck of window messages when using high polling rate mouse (8k).

These changes includes RIDEV_NOLEGACY flag to RegisterRawInputDevices, disabling legacy WindowProc messages for input device we register.

I had to fix issues with mouse input when m_raw_input is 0, and also issues that are including with lack of legacy messages 
that i managed to fix with disabling raw input (handling WM_KILLFOCUS, WM_SETFOCUS, mouse going away from client screen space (WM_MOUSELEAVE)).

Since the legacy messages are gone, i made mouse input fully raw when using m_raw_input 1 (handling buttons, scroll).

here is the result (m_raw_input 0 will create fps drops since it uses game's old behaviour):

https://github.com/user-attachments/assets/40b69069-132b-409f-8538-f48cfaeef68a

2024-11-09 22:17 UTC, wroyca requested changes

2024-11-09 22:17 UTC, wroyca commented on src/Components/Modules/RawMouse.cpp
> +			mouse_event_flag |= 0x10u;
don't we need to check for up as well? e.g. 'raw->data.mouse.usButtonFlags & (RI_MOUSE_BUTTON_5_DOWN | RI_MOUSE_BUTTON_5_UP)) != 0'

2024-11-09 22:54 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +			mouse_event_flag |= 0x10u;
yeah, fixed it now

2024-11-09 22:56 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +#define K_MWHEELUP 205
done

2024-11-09 23:23 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +		bool success = RegisterRawInputDevices(Rid, ARRAYSIZE(Rid), sizeof(Rid[0])) == TRUE;
added check for raw input being present.

2024-11-09 23:40 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +		bool success = RegisterRawInputDevices(Rid, ARRAYSIZE(Rid), sizeof(Rid[0])) == TRUE;
added error logging in case of failure.

2024-11-10 11:27 UTC, Rackover requested changes
Sorry to point out stuff that may not be coming from _your_ PR in particular, but It's also my first look at `RawMouse.cpp` so while we're here I figure we can
Other than that there are a few things that need adjustment and then once this passes building in CI i'll test it before merging 😃

2024-11-10 11:27 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
>  		static BYTE lpb[sizeof(RAWINPUT)];
This probably ought to be simply `static RAWINPUT lpb;` - this way the size is correct and no need for Reinterpret_cast below

2024-11-10 11:27 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
>  		auto* raw = reinterpret_cast<RAWINPUT*>(lpb);
`raw = &lpb;` (provided lpb is made the correct type)

2024-11-10 11:27 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
>  		GetRawInputData((HRAWINPUT)lParam, RID_INPUT, lpb, &dwSize, sizeof(RAWINPUTHEADER));
- Return value never handled (it can return -1 in case of error, or otherwise) - best to check that to avoid processing invalid mouse inputs
- `static_cast<>` or `reinterpret_cast<>` are preferred to C-Style casts `()`

2024-11-10 11:27 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
> +			PVOID pfnGetRawInputData = GetProcAddress(user32, "GetRawInputData");
These two are Windows XP functions so you can access them directl ywithout using GetModuleHandleA and GetProcAddress I think !

2024-11-10 11:27 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
> +		static auto r_fullscreen = Dvar::Var("r_fullscreen");
r_fullscreen is registered at R_Init, which is very early, so rather than declaring the Dvar (like you do for autopriority) I think you'd rather add this dvar to `Game::` and reference it directly.
It is directly access at the beginning of IN_MouseMove in the engine so I assume this is supposed to exist at that time

The address is 0x069F0DA0

2024-11-10 11:27 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
> +			GetWindowRect(Window::GetWindow(), &Rect);
Believe it or not, GetWindowRect can fail (check for == TRUE before doing anything with RECT, otherwise you're using unitialized struct)

2024-11-10 11:27 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
> +		Utils::Hook(0x48A0E6, IN_Frame, HOOK_CALL).install()->quick();
Random bit of review, feel free to mark this as resolved if due dilligence has been taken:
Please make sure nowhere in the IW4x client has these 3 addresses already hooked. Gamepad comes to mind as a module that hooks into INput frame in several places, so please make sure this is not disrpting another module (make sure gamepad is still usable and make sure these addresses are not mentioned elsewhere in the source code)

2024-11-10 11:27 UTC, Rackover commented on src/Game/System.cpp
> +		return *(int*)sysMsgTime_t;
This is a little bit ugly and hard to parse: 
- 0x64A3AC8 is the address of a variable named `g_wv` of type `WinVars_t`. This is probably the object you want to access instead of fetching the member sysMsgTime directly
- _t is a suffix for type and i'm not sure it's appropriate to name a variable like this
- C++ Cast (reinterpret/static) is preferred to C-Style (*)
- Wrong casing on the function name (?)

Probably a better option here is to properly hook g_wv (WinVars_t*) by its address, as a public member of Game::, then letting your other code access that variable's member directly (or through a function)

2024-11-10 11:33 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +			PVOID pfnGetRawInputData = GetProcAddress(user32, "GetRawInputData");
yeah, thats just a safety check that can be left out

2024-11-10 11:42 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +		Utils::Hook(0x48A0E6, IN_Frame, HOOK_CALL).install()->quick();
just rechecked those, all of them have only 1 reference in RawMouse.cpp

2024-11-10 12:14 UTC, L3D451R7 commented on src/Game/System.cpp
> +		return *(int*)sysMsgTime_t;
done

2024-11-10 12:14 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +			GetWindowRect(Window::GetWindow(), &Rect);
done

2024-11-10 12:15 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +		static auto r_fullscreen = Dvar::Var("r_fullscreen");
done, now it initializes all the DVars in IN_Init, and checks if DVar was inited - you can remove the initialization in IN_Init and code will not crash cause of that.

2024-11-10 12:15 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
>  		GetRawInputData((HRAWINPUT)lParam, RID_INPUT, lpb, &dwSize, sizeof(RAWINPUTHEADER));
done

2024-11-10 12:16 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
>  		auto* raw = reinterpret_cast<RAWINPUT*>(lpb);
done

2024-11-10 12:16 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
>  		static BYTE lpb[sizeof(RAWINPUT)];
done

2024-11-10 12:37 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +			PVOID pfnGetRawInputData = GetProcAddress(user32, "GetRawInputData");
just rechecked, MW2 (and iw4x) does not support windows older than XP - so yeah this check is completely useless.

2024-11-11 18:24 UTC, Rackover requested changes
Only very small stuff remains

2024-11-11 18:24 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
> +		int delta_x = cursor_pos.x - prev_cursor.x;
iw4x is camelCase  !

2024-11-11 18:24 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
> +				prev_cursor.y = window_center_y;
camelCase

2024-11-11 18:24 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
> +	void raw_mouse_value_t::ResetDelta()
Please prefer camelCase instead of snake_case, for type names too
The only exception is for dvar names and game structs wheree we try to stick to the game's convention (or lack thereof)

2024-11-11 18:24 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
> +#define RAW_MOUSE_VERBOSE 1
I suppose I understand the rationale behind having HIGH_POLLING_RATE_FIX as macro (is there ever a case where we _don't want_ the fix though?)

However Raw mouse verbose sounds like it should be a Dvar instead. Turning on or off mouse log should not require to recompile the software 🫡 

Please make it a Dvar if possible (with ::DVAR_SAVED flag maybye?)

2024-11-11 18:24 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
> +		R_FullScreen = Dvar::Var(0x069F0DA0);
nice, I didn't know about this constructor!

2024-11-11 22:03 UTC, Rackover requested changes
After testing this makes gamepad **non fonctional** compared to r4695
- Gamepad cannot be used to navigate in menus
- Gamepad is not recognized ingame either

I think the hooks you have made must conflict with something within gamepad support. Maybe they overwrite or something or are two wide. Try disabling the hooks you added and see if gamepad works again - reenable the most suspicious hook, and so on until stumbling on the one that breaks it

2024-11-12 03:32 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +	void raw_mouse_value_t::ResetDelta()
done.

2024-11-12 03:32 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +				prev_cursor.y = window_center_y;
done.

2024-11-12 03:32 UTC, L3D451R7 commented on src/Components/Modules/RawMouse.cpp
> +		int delta_x = cursor_pos.x - prev_cursor.x;
done.

2024-12-02 17:42 UTC, Rackover approved these changes

2024-12-02 17:42 UTC, merged

2024-12-02 17:42 UTC, Rackover commented
Tested, no undesirable side effects (mouse too shitty to test the high DPI)