Improved gentity struct.
iw4x/iw4x-client pull request #172
Opened 2024-12-04 19:37 UTC by Caball009

**What does this PR do?**

This improves the layout of the gentity_s struct.

**How does this PR change IW4x's behaviour?**

None of the existing code should be affected. I cannot find any references to gentity fields below gentity_s::count, so there shouldn't be any offset problems.

**Anything else we should know?**

This is based on iw4 xbox360 debug information. Some of the type and field names are my own as I couldn't find their actual names. The struct change should be helpful for the antilag pr:  https://github.com/iw4x/iw4x-client/pull/169#pullrequestreview-2479676404

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Mention any [related issues](https://github.com/iw4x/iw4x-client/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/iw4x/iw4x-client/blob/master/CODESTYLE.md)
- [x] Minimize the number of commits

2024-12-10 20:10 UTC, wroyca requested changes

2024-12-10 20:10 UTC, wroyca commented on src/Game/Structs.hpp
> +		int stage;
Type should be `MissileStage`

2024-12-10 20:10 UTC, wroyca commented on src/Game/Structs.hpp
> +		int team;
Type should be `team_t`

2024-12-10 22:14 UTC, wroyca commented on src/Game/Structs.hpp
> +		int stage;
```
enum MissileStage
{
  MISSILESTAGE_SOFTLAUNCH = 0x0,
  MISSILESTAGE_ASCENT = 0x1,
  MISSILESTAGE_DESCENT = 0x2,
};
```

2024-12-11 16:05 UTC, Caball009 commented on src/Game/Structs.hpp
> +		int team;
team_t already exists, but I changed the team field type to team_t.

2024-12-11 16:08 UTC, wroyca approved these changes

2024-12-20 19:46 UTC, Rackover approved these changes

2024-12-20 19:47 UTC, Rackover commented on src/Game/Structs.hpp
> +		int team;
team_t here too I suppose?

2024-12-22 17:42 UTC, Caball009 commented on src/Game/Structs.hpp
> +		int team;
I checked IW4, IW5 and T5 and none of them have this field as a team_t enum, but I still think it's quite likely to be a team_t.

2024-12-22 17:59 UTC, wroyca commented on src/Game/Structs.hpp
> +		int team;
Can confirm, spawner_ent_t doesn't use team_t on T5; perhaps it's best to leave it as is for now and see how the code references it.

2024-12-23 00:06 UTC, merged

2024-12-23 00:07 UTC, Rackover commented on src/Game/Structs.hpp
> +		int team;
OK; feel free to open another PR if this turns out to be team_t.  Even if that's not exactly what's in the symbols, if that's what the game does internally that it makes sense to have it be a team_t