[Stats]: Fix code and save stats to mods folder when needed
iw4x/iw4x-client pull request #181
Opened 2024-12-17 20:05 UTC by diamante0018

**What does this PR do?**

Big fix like the title says

**How does this PR change IW4x's behaviour?**

Restore intended behaviour

**Anything else we should know?**

No

**Did you check all the boxes?**

- [X] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [X] Mention any [related issues](https://github.com/iw4x/iw4x-client/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [X] Follow our [coding conventions](https://github.com/iw4x/iw4x-client/blob/master/CODESTYLE.md)
- [X] Minimize the number of commits

2024-12-17 20:16 UTC, diamante0018 commented
good 
![image](https://github.com/user-attachments/assets/93982793-3e84-4656-9b22-eb8f7164cfdb)

2025-01-17 21:27 UTC, wroyca requested changes

2025-01-17 21:27 UTC, wroyca commented on src/Components/Modules/Stats.cpp
> +		static std::string modsFolder; // This var is static to ensure the string pointer does not become nullptr after this function exits
It's ok to drop static here, the real issue (if any) could arise from using the pointer (c_str()) outside the function while the string itself is modified, but that's unrelated to the static keyword :saluting_face:

2025-01-17 21:29 UTC, diamante0018 commented on src/Components/Modules/Stats.cpp
> +		static std::string modsFolder; // This var is static to ensure the string pointer does not become nullptr after this function exits
Sure. I'll apply the change tomorrow

2025-01-18 13:28 UTC, diamante0018 commented on src/Components/Modules/Stats.cpp
> +		static std::string modsFolder; // This var is static to ensure the string pointer does not become nullptr after this function exits
I  retraced my steps a bit and pushed a new commit, I think this should be good because there is no static  var and fixes the issue

2025-01-18 13:44 UTC, diamante0018 commented
![image](https://github.com/user-attachments/assets/f6c3654d-6e95-4b62-81f0-8df2a7e38434)
confirm it's working

2025-01-18 14:21 UTC, wroyca approved these changes

2025-01-18 14:21 UTC, merged