Added new gsc functions and methods, dvars and changed some code.
IW4x/iw4x-client pull request #36
Opened 2020-07-23 03:46 UTC by Joelrau

**Functions**: _fileWrite_, _fileRead_, _fileExists_, _fileRemove_
**Methods**: _getIP_, _getPing_
**Dvars**: _g_playerCollision_, _g_playerEjection_, _r_specularCustomMaps_

There are some changes to the general code too.

2020-09-01 22:36 UTC, ineedbots commented
Would adding script functions 'HTTPGet' and 'HTTPPost' be something appropriate for the client?

2020-09-02 06:47 UTC, momo5502 commented
> Would adding script functions 'HTTPGet' and 'HTTPPost' be something appropriate for the client?

That already exists: https://github.com/IW4x/iw4x-client/blob/50e93d7f2f8d68e08f13b28a59e175eb4046e976/src/Components/Modules/Download.cpp#L969

2020-09-02 07:01 UTC, ineedbots commented
Ah, I missed that, thanks.

But what about POST?

2020-09-02 07:18 UTC, momo5502 commented
> Ah, I missed that, thanks.
> 
> But what about POST?

You can implement that yourself, but I mean who needs post. You can do everything with get as well. It's a game and not a webbrowser.

2020-09-02 08:08 UTC, momo5502 approved these changes

2020-09-02 08:08 UTC, momo5502 commented on src/Utils/CSV.cpp
> +			else if (!isString && (row[i] == '#' || (row[i] == '/' && row[i+1] == '/') ) && allowComments) // Skip comments. I know CSVs usually don't have comments, but in this case it's useful
What if row[i] is the last character in the string? row[i+1] would overflow...

2020-09-02 08:11 UTC, momo5502 requested changes

2020-09-02 08:11 UTC, momo5502 commented on src/Components/Modules/Client.cpp
> +			if (Game::FS_FileExists(path.data()) == false)
There is a Filesystem wrapper which handles all that way more cleanly

2020-09-02 08:21 UTC, Joelrau commented on src/Utils/CSV.cpp
> +			else if (!isString && (row[i] == '#' || (row[i] == '/' && row[i+1] == '/') ) && allowComments) // Skip comments. I know CSVs usually don't have comments, but in this case it's useful
Then should it be || (row[i] == '/' && row[i-1] == '/') 
So it would check if the current row[i] is "/" and the previous is "/" too?

Or would there be a better implementation? Thanks.

2020-09-02 08:37 UTC, momo5502 commented on src/Utils/CSV.cpp
> +			else if (!isString && (row[i] == '#' || (row[i] == '/' && row[i+1] == '/') ) && allowComments) // Skip comments. I know CSVs usually don't have comments, but in this case it's useful
That would result in an underflow if i is 0.
Just make sure that i is not the last character like this: 
`(row[i] == '/' && (i + 1) < row.size() && row[i+1] == '/')`

2020-09-02 08:41 UTC, Joelrau commented on src/Components/Modules/Client.cpp
> +			if (Game::FS_FileExists(path.data()) == false)
I don't quite understand. Is (Game::FS_FileExists(path.data()) == false) not good?
Are you saying (FileSystem::FileReader(path.data()).exists()) would be better?

2020-09-02 08:42 UTC, momo5502 commented on src/Components/Modules/Client.cpp
> +			if (Game::FS_FileExists(path.data()) == false)
Yes, and that for all the Filesystem actions you do in this commit

2020-09-02 08:46 UTC, Joelrau commented on src/Components/Modules/Client.cpp
> +			if (Game::FS_FileExists(path.data()) == false)
Okay, I will do as you say and test it ingame.

2020-09-02 10:24 UTC, Joelrau commented on src/Components/Modules/Client.cpp
> +			if (Game::FS_FileExists(path.data()) == false)
Updated the pull request.

2020-09-02 11:02 UTC, momo5502 approved these changes

2020-09-02 11:02 UTC, merged