Compatibility and improvements for Bot Warfare
iw4x/iw4x-client pull request #68
Opened 2023-12-05 22:41 UTC by ineedbots

**What does this PR do?**

My Bot Warfare mod (https://github.com/ineedbots/iw4_bot_warfare) will be compatible with this client with these changes. Bots will be able to press the Use button on objects, bots will be able to use alt weaponry properly. Added `botMeleeParams` builtin to allow bots to melee lung

**How does this PR change IW4x's behaviour?**

Nothing is breaking.

**Anything else we should know?**

Max SL string length is actually 65535, not 1023, this is a required change for Bot Warfare reading waypoints. "scriptdata/" is NOT added to filepath if it already exists in the argument.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Mention any [related issues](https://github.com/XLabsProject/iw4x-client/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/XLabsProject/iw4x-client/blob/master/CODESTYLE.md)
- [x] Minimize the number of commits

2023-12-05 22:58 UTC, diamante0018 requested changes

2023-12-05 22:58 UTC, diamante0018 commented on src/Components/Modules/GSC/IO.cpp
> +		char line[65536]{};
This change should be undone
There is no sane person that goes to the great length to read a file in bits as a stream than just uses such a big buffer, ON THE STACK???!!!

2023-12-05 23:06 UTC, diamante0018 commented on src/Components/Modules/GSC/IO.cpp
> +		char line[65536]{};
Resolved

2023-12-05 23:14 UTC, Rackover reviewed
Looks good and I will test it, if it runs i see no problem merging that after the usual nitpicky formatting has been taken care of 😗

2023-12-05 23:14 UTC, Rackover commented on src/Components/Modules/GSC/IO.cpp
> +			spath = "scriptdata/" + spath;
Maybe turning `scriptdata` into a constant would be nice since it appears occasionally throughout this file, rather than repeating the string

2023-12-05 23:14 UTC, Rackover commented on src/Components/Modules/Bots.cpp
> +		userCmd.primaryWeaponForAltMode = g_botai[cl - Game::svs_clients].lastAltWeapon;
i skimmed through the function and you use `cl - Game::svs_clients` multiple times, same thing I think it would be nice if it was factorized into a single variable at the beginning of your function

2023-12-05 23:14 UTC, Rackover commented on src/Components/Modules/Bots.cpp
> +				auto num_weaps = Game::BG_GetNumWeapons();
sir this is camelCase territory

2023-12-05 23:14 UTC, Rackover commented on src/Components/Modules/Bots.cpp
> +		return false;
Does this have no other consequences?  What was the original gentity check at 0x4B3D00 done for? 🤔

2023-12-05 23:22 UTC, Rackover commented on src/Components/Modules/Bots.cpp
> +		return false;
thx!! if you can add a comment in the code saying that then it's nice.
Do you know if this could mess up with testclients (non-bw bots) ?

2023-12-13 08:59 UTC, Rackover approved these changes

2023-12-13 09:00 UTC, merged