feature: auto updater!
iw4x/iw4x-client pull request #76
Opened 2023-12-29 22:21 UTC by diamante0018

**What does this PR do?**

- Auto updater
- Fixes singleton component memory leak

2024-01-11 22:29 UTC, Rackover requested changes

2024-01-11 22:29 UTC, Rackover commented on src/Components/Modules/Updater.cpp
> +			Utils::OpenUrl("https://forum.alterware.dev/t/how-to-install-the-alterware-launcher/56");
Sorry to be extra annoying but i would like to ask you to please turn all those addresses and filename (http://forum, alterware-launcher.exe, the github repo URL, etc...) into variables or macros at the beginning of the file or in the headerfile, however you like it. thanks! 

Other than that it's good to go, so whenever it's done i will test it and merge it.
Does this have a dependency on any IW4x rawfile PR you would want this to get tested with? So I can test both together & greenlight both!

2024-01-11 22:29 UTC, Rackover commented on src/Components/Modules/Updater.cpp
> +				Logger::Print(".iw4xrevision does not exist. Notifying the user an update is available\n");
missed an occasion to std::format here
`Logger::Print("{} does not exist", revisionFile)`

2024-01-12 08:48 UTC, diamante0018 commented on src/Components/Modules/Updater.cpp
> +			Utils::OpenUrl("https://forum.alterware.dev/t/how-to-install-the-alterware-launcher/56");
Yeah both should be merged at the same time

2024-01-20 12:02 UTC, Rackover requested changes
Two small things to address and then i'll merge it with my eyes closed

2024-01-20 12:02 UTC, Rackover commented on src/Components/Modules/Updater.cpp
> +			std::string revision;
no `{}` ?

2024-01-20 12:02 UTC, Rackover commented on src/Components/Modules/Updater.cpp
> +				Logger::Print("GitHub sent an invalid reply\n");
Its preferable not to have two different errors print out the same message. You can add (malformed JSON) on the first one and (missing tag_name) on the second for instance.

2024-01-20 12:46 UTC, diamante0018 commented on src/Components/Modules/Updater.cpp
> +			std::string revision;
That has no functional change: {} -> calls the default ctor which is the same as my code.

2024-01-20 13:45 UTC, Rackover approved these changes

2024-01-20 13:55 UTC, merged