feat: add poolUsage(s)/assetCount commands
iw4x/iw4x-client pull request #89
Opened 2024-02-08 12:04 UTC by Lierrmm

**What does this PR do?**

Adds 3 new commands that can be used for seeing the total number of xassets used.

- poolUsages
- poolUsage
- assetCount

**How does this PR change IW4x's behaviour?**

Existing behavior does not change.

- poolUsages
  - Lists the usage/total count of each xasset type
- poolUsage `<number>`
  - Lists the usage/total count of the specified xasset type
- assetCount
  - List the total amount of xassets used/total xasset limit

- poolUsages
![image](https://github.com/iw4x/iw4x-client/assets/13552261/03c5236b-e381-4f5f-81fb-f58027254603)

- poolUsage `<number>`
![image](https://github.com/iw4x/iw4x-client/assets/13552261/380078b5-76ea-4564-8384-e62db529c650)

- assetCount
![image](https://github.com/iw4x/iw4x-client/assets/13552261/5889bb36-c7c3-444a-80d8-5c9e90bb5c11)

**Anything else we should know?**

N/A

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Mention any [related issues](https://github.com/XLabsProject/iw4x-client/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/XLabsProject/iw4x-client/blob/master/CODESTYLE.md)
- [x] Minimize the number of commits

2024-02-11 19:29 UTC, Rackover requested changes

2024-02-11 19:29 UTC, Rackover commented on src/Components/Modules/FastFiles.cpp
> +		Command::Add("poolUsages", []()
If you could make those commands 3 functions instead of defining their body in the constructor of FastFiles that would be better (when I add functions to IW4x that's what I'm trying to do from now on).

2024-02-11 19:29 UTC, Rackover commented on src/Components/Modules/FastFiles.cpp
> +	void enum_assets(const Game::XAssetType type, const std::function<void(Game::XAssetHeader, void*)> callback, const bool includeOverride)
I'm not sure that function is necessary (it's basically a forwarder to Game::DB_EnumXAsset, i don't feel like it does much more?) but asssuming it would be:
- I think this belongs in AssetHandler not FastFiles
- PascalCase for functions not snake_case please !
- Add it to the class as a private function rather than defining it in the CPP

2024-02-14 18:05 UTC, diamante0018 requested changes

2024-05-06 17:28 UTC, diamante0018 requested changes
I'm porting this code to a fork to test it out and there are several issues with it besides the several issues already pointed out

2024-05-06 17:28 UTC, diamante0018 commented on src/Components/Modules/FastFiles.cpp
> +	void enum_assets(const Game::XAssetType type, const std::function<void(Game::XAssetHeader, void*)> callback, const bool includeOverride)
CamelCase + defined function as static member of fastfiles

2024-05-06 17:28 UTC, diamante0018 commented on src/Components/Modules/FastFiles.cpp
> +			const auto type = static_cast<Game::XAssetType>(std::atoi(params->get(1)));
lack of bounds checking i  can enter a negative number in the console and this code will happily take it in

2024-05-06 17:28 UTC, diamante0018 commented on src/Game/Database.hpp
> +	typedef void(*DB_EnumXAssets_Internal_t)(XAssetType type, void(*)(XAssetHeader, void*), const void* userdata, bool overrides);
modify your code to match the game's function definitions not the other way around

2024-08-26 12:22 UTC, Rackover commented
@Lierrmm Hello, any news? 😄

2025-01-18 19:42 UTC, closed without merging

2025-01-18 19:44 UTC, wroyca commented
This PR has been stalled for a long time. Closing it for now, but feel free to reopen it if you’d like to continue working on it, @Lierrmm